config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'products#index'

  resources :carts, only: [:index] do
    get 'add_to_cart', on: :collection
    get 'destroy_cart', on: :collection
    delete 'remove_product', on: :collection
    get 'increase_quantity', on: :collection
    get 'reduce_quantity', on: :collection
  end

  resources :categories
  resources :brands
  resources :products


  namespace :admin do
    get '/', to: 'admin#index'
    resources :categories
    resources :products
    resources :brands
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  has_ancestry
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category, counter_cache: :products_count
  belongs_to :brand, counter_cache: :products_count
  mount_uploaders :images, ImageUploader
end

app/controllers/admin/admin_controller.rb
class Admin::AdminController < ApplicationController
  before_action :authenticate_admin!
  
  layout "admin"

  def index
    redirect_to admin_products_path
  end

end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < Admin::AdminController
  
  def index
    @brands = Brand.all
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new(brands_params)
    if @brand.save
      redirect_to admin_brands_path
    else
      render 'new'
    end
  end

  def edit
    @brand = Brand.find(params[:id])
  end

  def update
    @brand = Brand.find(params[:id])
    if @brand.update(brands_params)
      redirect_to admin_brands_path
    else
      render 'edit'
    end
  end

  def destroy
    @brand = Brand.find(params[:id])
    @brand.destroy
    redirect_to :back
  end

  private

  def brands_params
    params.require(:brand).permit(:title)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def show
    @brand = Brand.find(params[:id])
    @products = @brand.products.paginate(page: params[:page], per_page: 1).order(created_at: :desc)
    @brands = Brand.all
    @categories = Category.all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def add_to_cart
    product_id = params[:product_id]
    quantity = params[:quantity]
    add_to_session(product_id, quantity.to_i)
  end

  def index
    @carts = session[:carts]
  end

  def remove_product
    delete_product(params[:product_id])
    redirect_to :back
  end

  def destroy_cart
    session[:carts] = {}
    redirect_to :back
  end

  def increase_quantity
    @carts = session[:carts]
    add_quantity(params[:product_id], params[:quantity].to_i)
  end

  def reduce_quantity
    @carts = session[:carts]
    subtract_quantity(params[:product_id], params[:quantity].to_i)
  end

  private

  def add_to_session(product_id, quantity)
    return session[:carts] = {product_id => quantity} if session[:carts].nil?
    return session[:carts][product_id] += quantity if session[:carts].has_key?(product_id)
    session[:carts] = session[:carts].merge({product_id => quantity})
  end

  def delete_product(product_id)
    session[:carts].delete product_id
  end

  def add_quantity(product_id, quantity)
    session[:carts][product_id] += quantity.to_i
  end

  def subtract_quantity(product_id, quantity)
    if session[:carts][product_id] == 1
      return session[:carts]
    else
      session[:carts][product_id] -= quantity.to_i
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.paginate(page: params[:page], per_page: 1).order(created_at: :desc)
    @categories = Category.all
    @brands = Brand.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show

  end
end

app/controllers/pay_controller.rb
class PayController < ApplicationController
	def epay
		path_to_yaml = Rails.root.join('config', 'epay.yml')
		epay_credentials = YAML.load_file(path_to_yaml)
		amount = 12 #hard code
		# здесь вы фиксируете Order_ID, который вы передадите банку
		# и по которому вы сможете в дальнейшем найти нужный платеж
		# и пользователя, чтобы зачислить деньги ему на счет
		payment_request = PaymentRequest.create! do |r|
			r.user = current_user
			r.amount = amount
		end
		order_id = payment_request.id
		epay_credentials.merge!({ amount: amount, order_id: order_id })
		epay = KazkomEpay::Epay.setup(epay_credentials)
		@base64_encoded_xml = epay.base64_encoded_signed_xml
	end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	def process_payment
	  xml = params[:response]

	  epay_response_is_okay = KazkomEpay::Epay.check_signed_xml xml
	  if epay_response_is_okay
	    epay_response = Hash.from_xml(xml)['document']['bank']

	    begin
	      ActiveRecord::Base.transaction do
	        # Задача этого блока - увеличить счет пользователя

	        # Нужно найти Order_ID, который вы создали на этапе формировани
	        # XML для отправки в ePay.
	        # Например так (при условии, что у вас есть модель PaymentRequest):
	        payment_request = PaymentRequest.find epay_response['customer']['merchant']['order']['order_id']

	        # из него вы можете выяснить, счет какого пользователя увеличить:
	        user = payment_request.user
	      end
	    rescue => e
	      # Что-то пошло не так, зафиксируйте это в логах и сделайте все, чтобы
	      # вы об этом узнали (отошлите себе уведомление и пр.)
	      Rails.logger.fatal "Что-то пошло не так при оплате через ePay. Данные: " + params.to_json

	      # ...
	    end
	  else
	    # Подпись оказалась неверной. Возможно, вас пытаются взломать
	  end

	  # Обязательно выведите "0" и ничего больше, это требование ePay
	  render text: "0"
	end
end

app/controllers/products_controller.rb
class ProductsController < BaseController
  # skip_before_action check_current_user only: [:index, :show]

  def index
    @products = Product.paginate(page: params[:page], per_page: 1).order(id: :desc)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/admin/admin_helper.rb
module Admin::AdminHelper
end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pay_helper.rb
module PayHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/brands/edit.html.erb
<div class="form-block">
  <h3> Редактировать бренд</h3>
  <%= form_for [:admin, @brand] do |f| %>

      <div class="form-row">
        <%= f.label :title, 'Название' %>
        <%= f.text_field :title, placeholder: 'Название' %>
      </div>

      <div class="form-row">
        <input type="submit" class="submit_btn" value="Обновить" >
      </div>
  <% end %>
</div>

app/views/admin/brands/index.html.erb
<h4><%= link_to 'Добавить новый бренд', new_admin_brand_path %></h4>
<hr>
<h4>Все бренды</h4>

<table class="table table-condensed">
  <tr>
    <td><b>Название</b></td>
    <td><b>Действия</b></td>
  </tr>
  <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.title %></td>
        <td>
          <%= link_to 'Редактировать', edit_admin_brand_path(brand) %> /
          <%= link_to 'Удалить', admin_brand_path(brand), method: :delete, data: {confirm: 'Вы уверены?'} %>
        </td>
      </tr>
  <% end %>
</table>

app/views/admin/brands/new.html.erb
<div class="form-block">
  <h3> Добавить бренд</h3>
  <%= form_for [:admin, @brand] do |f| %>

      <div class="form-row">
        <%= f.label :title, 'Название' %>
        <%= f.text_field :title, placeholder: 'Название' %>
      </div>

      <div class="form-row">
        <input type="submit" class="submit_btn" value="Добавить" >
      </div>
  <% end %>
</div>

app/views/brands/show.html.erb
<section id="advertisement">
  <div class="container">
    <img src="<%= image_path '/uploads/shop/advertisement.jpg' %>" alt="" />
  </div>
</section>

<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="left-sidebar">
          <h2>Category</h2>
          <div class="panel-group category-products" id="accordian"><!--category-productsr-->
            <% @categories.each do |category| %>
                <div class="panel panel-default">
                  <div class="panel-heading">
                    <h4 class="panel-title"><a href="<%= category_path(category) %>"><%= category.title %></a></h4>
                  </div>
                </div>
            <% end %>
          </div><!--/category-products-->
          <div class="brands_products"><!--brands_products-->
            <h2>Brands</h2>
            <div class="brands-name">
              <ul class="nav nav-pills nav-stacked">
                <% @brands.each do |brand| %>
                    <li><a href="<%= brand_path(brand) %>"> <span class="pull-right">(<%= brand.products_count.nil?  ? '0' : brand.products_count  %>)</span><%= brand.title %></a></li>
                <%end %>
              </ul>
            </div>
          </div><!--/brands_products-->

          <div class="price-range">
            <h2>Price Range</h2>
            <div class="well">
              <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
              <b>$ 0</b> <b class="pull-right">$ 600</b>
            </div>
          </div>

          <div class="shipping text-center"><!--shipping-->
            <img src="<%= image_path '/uploads/home/shipping.jpg' %> " alt="" />
          </div><!--/shipping-->
        </div>
      </div>

      <!--products_section-->
      <div class="col-sm-9 padding-right">
        <div class="features_items"><!--features_items-->
          <h2 class="title text-center"><%= @brand.title %></h2>
          <% @products.each do |product| %>
              <div class="col-sm-4">
                <div class="product-image-wrapper">
                  <div class="single-products">
                    <div class="productinfo text-center">
                      <a href="<%= product_path(product) %>">
                        <img class="img-responsive" src="<%= product.images[0].url(:main_page_size) %>" alt="<%= product.title %>">
                      </a>
                      <h2><%= product.price %></h2>
                      <p><%= product.title %></p>
                      <a href="<%= add_to_cart_carts_path(product_id: product.id, quantity: 1) %>" data-remote="true" class="btn btn-default add-to-cart">
                        <i class="fa fa-shopping-cart"></i>
                        Добавить в корзину
                      </a>
                      <span class="in_cart">Добавлено в корзину</span>
                    </div>
                  </div>
                  <div class="choose">
                    <ul class="nav nav-pills nav-justified">
                      <li><a href=""><i class="fa fa-plus-square"></i>Add to wishlist</a></li>
                      <li><a href=""><i class="fa fa-plus-square"></i>Add to compare</a></li>
                    </ul>
                  </div>
                </div>
              </div>
          <% end  %>

          <div class="clearfix">
            <ul class="pagination">
              <li><%= will_paginate @products %></li>
            </ul>
          </div>

        </div><!--features_items-->
      </div>
    </div>
  </div>
</section>