config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root 'products#index'

  resources :carts, only: [:index] do
    get 'add_to_cart', on: :collection
    get 'destroy_cart', on: :collection
    delete 'remove_product', on: :collection
    get 'increase_quantity', on: :collection
    get 'reduce_quantity', on: :collection
  end

  resources :categories
  resources :brands
  resources :products


  namespace :admin do
    get '/', to: 'admin#index'
    resources :categories
    resources :products
    resources :brands
  end

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
  has_ancestry
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category, counter_cache: :products_count
  belongs_to :brand, counter_cache: :products_count
  mount_uploaders :images, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def show
    @brand = Brand.find(params[:id])
    @products = @brand.products.paginate(page: params[:page], per_page: 1).order(created_at: :desc)
    @brands = Brand.all
    @categories = Category.all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def add_to_cart
    product_id = params[:product_id]
    quantity = params[:quantity]
    add_to_session(product_id, quantity.to_i)
  end

  def index
    @carts = session[:carts]
  end

  def remove_product
    delete_product(params[:product_id])
    redirect_to :back
  end

  def destroy_cart
    session[:carts] = {}
    redirect_to :back
  end

  def increase_quantity
    @carts = session[:carts]
    add_quantity(params[:product_id], params[:quantity].to_i)
  end

  def reduce_quantity
    @carts = session[:carts]
    subtract_quantity(params[:product_id], params[:quantity].to_i)
  end

  private

  def add_to_session(product_id, quantity)
    return session[:carts] = {product_id => quantity} if session[:carts].nil?
    return session[:carts][product_id] += quantity if session[:carts].has_key?(product_id)
    session[:carts] = session[:carts].merge({product_id => quantity})
  end

  def delete_product(product_id)
    session[:carts].delete product_id
  end

  def add_quantity(product_id, quantity)
    session[:carts][product_id] += quantity.to_i
  end

  def subtract_quantity(product_id, quantity)
    if session[:carts][product_id] == 1
      return session[:carts]
    else
      session[:carts][product_id] -= quantity.to_i
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.paginate(page: params[:page], per_page: 1).order(created_at: :desc)
    @categories = Category.all
    @brands = Brand.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show

  end
end

app/controllers/pay_controller.rb
class PayController < ApplicationController
	def epay
		path_to_yaml = Rails.root.join('config', 'epay.yml')
		epay_credentials = YAML.load_file(path_to_yaml)
		amount = 12 #hard code
		# здесь вы фиксируете Order_ID, который вы передадите банку
		# и по которому вы сможете в дальнейшем найти нужный платеж
		# и пользователя, чтобы зачислить деньги ему на счет
		payment_request = PaymentRequest.create! do |r|
			r.user = current_user
			r.amount = amount
		end
		order_id = payment_request.id
		epay_credentials.merge!({ amount: amount, order_id: order_id })
		epay = KazkomEpay::Epay.setup(epay_credentials)
		@base64_encoded_xml = epay.base64_encoded_signed_xml
	end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	def process_payment
	  xml = params[:response]

	  epay_response_is_okay = KazkomEpay::Epay.check_signed_xml xml
	  if epay_response_is_okay
	    epay_response = Hash.from_xml(xml)['document']['bank']

	    begin
	      ActiveRecord::Base.transaction do
	        # Задача этого блока - увеличить счет пользователя

	        # Нужно найти Order_ID, который вы создали на этапе формировани
	        # XML для отправки в ePay.
	        # Например так (при условии, что у вас есть модель PaymentRequest):
	        payment_request = PaymentRequest.find epay_response['customer']['merchant']['order']['order_id']

	        # из него вы можете выяснить, счет какого пользователя увеличить:
	        user = payment_request.user
	      end
	    rescue => e
	      # Что-то пошло не так, зафиксируйте это в логах и сделайте все, чтобы
	      # вы об этом узнали (отошлите себе уведомление и пр.)
	      Rails.logger.fatal "Что-то пошло не так при оплате через ePay. Данные: " + params.to_json

	      # ...
	    end
	  else
	    # Подпись оказалась неверной. Возможно, вас пытаются взломать
	  end

	  # Обязательно выведите "0" и ничего больше, это требование ePay
	  render text: "0"
	end
end

app/controllers/products_controller.rb
class ProductsController < BaseController
  # skip_before_action check_current_user only: [:index, :show]

  def index
    @products = Product.paginate(page: params[:page], per_page: 1).order(id: :desc)
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pay_helper.rb
module PayHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/shared/_sidebar.html.erb
<div class="sidebar_list_block">
<ul>
  <li><%= link_to 'Brandhouse', root_path %></li>

  <li class="<%= 'active' if controller_name == 'products' %>"><%= link_to 'Все продукты', admin_products_path %></li>

  <li class="<%= 'active' if controller_name == 'categories' %>"><%= link_to 'Все категории', admin_categories_path %></li>

  <li class="<%= 'active' if controller_name == 'brands' %>"><%= link_to 'Все бренды', admin_brands_path %></li>
</ul>
</div>

app/views/shared/_blog.html.erb
<section>
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <%= render 'shared/sideBar' %>
      </div>
      <div class="col-sm-9">
        <div class="blog-post-area">
          <h2 class="title text-center">Latest From our Blog</h2>
          <div class="single-blog-post">
            <h3>Girls Pink T Shirt arrived in store</h3>
            <div class="post-meta">
              <ul>
                <li><i class="fa fa-user"></i> Mac Doe</li>
                <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                <li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
              </ul>
								<span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
            </div>
            <a href="">
              <img src="<%= image_path '/uploads/blog/blog-one.jpg' %>" alt="">
            </a>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
            <a  class="btn btn-primary" href="">Read More</a>
          </div>
          <div class="single-blog-post">
            <h3>Girls Pink T Shirt arrived in store</h3>
            <div class="post-meta">
              <ul>
                <li><i class="fa fa-user"></i> Mac Doe</li>
                <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                <li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
              </ul>
								<span>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-half-o"></i>
								</span>
            </div>
            <a href="">
              <img src="<%= image_path '/uploads/blog/blog-two.jpg' %>" alt="">
            </a>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
            <a  class="btn btn-primary" href="">Read More</a>
          </div>
          <div class="single-blog-post">
            <h3>Girls Pink T Shirt arrived in store</h3>
            <div class="post-meta">
              <ul>
                <li><i class="fa fa-user"></i> Mac Doe</li>
                <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                <li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
              </ul>
								<span>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star"></i>
									<i class="fa fa-star-half-o"></i>
								</span>
            </div>
            <a href="">
              <img src="<%= image_path '/uploads/blog/blog-three.jpg' %>" alt="">
            </a>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
            <a  class="btn btn-primary" href="">Read More</a>
          </div>
          <div class="pagination-area">
            <ul class="pagination">
              <li><a href="" class="active">1</a></li>
              <li><a href="">2</a></li>
              <li><a href="">3</a></li>
              <li><a href=""><i class="fa fa-angle-double-right"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_cart.html.erb
<section id="cart_items">
  <div class="container">
    <div class="breadcrumbs">
      <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li class="active">Shopping Cart</li>
      </ol>
    </div>
    <div class="table-responsive cart_info">
      <table class="table table-condensed">
        <thead>
        <tr class="cart_menu">
          <td class="image">Item</td>
          <td class="description"></td>
          <td class="price">Price</td>
          <td class="quantity">Quantity</td>
          <td class="total">Total</td>
          <td></td>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td class="cart_product">
            <a href=""><img src="<%= image_path '/uploads/cart/one.png' %>" alt=""></a>
          </td>
          <td class="cart_description">
            <h4><a href="">Colorblock Scuba</a></h4>
            <p>Web ID: 1089772</p>
          </td>
          <td class="cart_price">
            <p>$59</p>
          </td>
          <td class="cart_quantity">
            <div class="cart_quantity_button">
              <a class="cart_quantity_up" href=""> + </a>
              <input class="cart_quantity_input" type="text" name="quantity" value="1" autocomplete="off" size="2">
              <a class="cart_quantity_down" href=""> - </a>
            </div>
          </td>
          <td class="cart_total">
            <p class="cart_total_price">$59</p>
          </td>
          <td class="cart_delete">
            <a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
          </td>
        </tr>

        </tbody>
      </table>
    </div>
  </div>
</section> <!--/#cart_items-->

<section id="do_action">
  <div class="container">
    <div class="heading">
      <h3>What would you like to do next?</h3>
      <p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
    </div>
    <div class="row">
      <div class="col-sm-6">
        <div class="chose_area">
          <ul class="user_option">
            <li>
              <input type="checkbox">
              <label>Use Coupon Code</label>
            </li>
            <li>
              <input type="checkbox">
              <label>Use Gift Voucher</label>
            </li>
            <li>
              <input type="checkbox">
              <label>Estimate Shipping & Taxes</label>
            </li>
          </ul>
          <ul class="user_info">
            <li class="single_field">
              <label>Country:</label>
              <select>
                <option>United States</option>
                <option>Bangladesh</option>
                <option>UK</option>
                <option>India</option>
                <option>Pakistan</option>
                <option>Ucrane</option>
                <option>Canada</option>
                <option>Dubai</option>
              </select>

            </li>
            <li class="single_field">
              <label>Region / State:</label>
              <select>
                <option>Select</option>
                <option>Dhaka</option>
                <option>London</option>
                <option>Dillih</option>
                <option>Lahore</option>
                <option>Alaska</option>
                <option>Canada</option>
                <option>Dubai</option>
              </select>

            </li>
            <li class="single_field zip-field">
              <label>Zip Code:</label>
              <input type="text">
            </li>
          </ul>
          <a class="btn btn-default update" href="">Get Quotes</a>
          <a class="btn btn-default check_out" href="">Continue</a>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="total_area">
          <ul>
            <li>Cart Sub Total <span>$59</span></li>
            <li>Eco Tax <span>$2</span></li>
            <li>Shipping Cost <span>Free</span></li>
            <li>Total <span>$61</span></li>
          </ul>
          <a class="btn btn-default update" href="">Update</a>
          <a class="btn btn-default check_out" href="">Check Out</a>
        </div>
      </div>
    </div>
  </div>
</section><!--/#do_action-->

app/views/shared/_checkout.html.erb
<section id="cart_items">
  <div class="container">
    <div class="breadcrumbs">
      <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li class="active">Check out</li>
      </ol>
    </div><!--/breadcrums-->

    <div class="step-one">
      <h2 class="heading">Step1</h2>
    </div>
    <div class="checkout-options">
      <h3>New User</h3>
      <p>Checkout options</p>
      <ul class="nav">
        <li>
          <label><input type="checkbox"> Register Account</label>
        </li>
        <li>
          <label><input type="checkbox"> Guest Checkout</label>
        </li>
        <li>
          <a href=""><i class="fa fa-times"></i>Cancel</a>
        </li>
      </ul>
    </div><!--/checkout-options-->

    <div class="register-req">
      <p>Please use Register And Checkout to easily get access to your order history, or use Checkout as Guest</p>
    </div><!--/register-req-->

    <div class="shopper-informations">
      <div class="row">
        <div class="col-sm-3">
          <div class="shopper-info">
            <p>Shopper Information</p>
            <form>
              <input type="text" placeholder="Display Name">
              <input type="text" placeholder="User Name">
              <input type="password" placeholder="Password">
              <input type="password" placeholder="Confirm password">
            </form>
            <a class="btn btn-primary" href="">Get Quotes</a>
            <a class="btn btn-primary" href="">Continue</a>
          </div>
        </div>
        <div class="col-sm-5">
          <div class="bill-to">
            <p>Bill To</p>
            <div class="form-one">
              <form>
                <input type="text" placeholder="Company Name">
                <input type="text" placeholder="Email*">
                <input type="text" placeholder="Title">
                <input type="text" placeholder="First Name *">
                <input type="text" placeholder="Middle Name">
                <input type="text" placeholder="Last Name *">
                <input type="text" placeholder="Address 1 *">
                <input type="text" placeholder="Address 2">
              </form>
            </div>
            <div class="form-two">
              <form>
                <input type="text" placeholder="Zip / Postal Code *">
                <select>
                  <option>-- Country --</option>
                  <option>United States</option>
                  <option>Bangladesh</option>
                  <option>UK</option>
                  <option>India</option>
                  <option>Pakistan</option>
                  <option>Ucrane</option>
                  <option>Canada</option>
                  <option>Dubai</option>
                </select>
                <select>
                  <option>-- State / Province / Region --</option>
                  <option>United States</option>
                  <option>Bangladesh</option>
                  <option>UK</option>
                  <option>India</option>
                  <option>Pakistan</option>
                  <option>Ucrane</option>
                  <option>Canada</option>
                  <option>Dubai</option>
                </select>
                <input type="password" placeholder="Confirm password">
                <input type="text" placeholder="Phone *">
                <input type="text" placeholder="Mobile Phone">
                <input type="text" placeholder="Fax">
              </form>
            </div>
          </div>
        </div>
        <div class="col-sm-4">
          <div class="order-message">
            <p>Shipping Order</p>
            <textarea name="message"  placeholder="Notes about your order, Special Notes for Delivery" rows="16"></textarea>
            <label><input type="checkbox"> Shipping to bill address</label>
          </div>
        </div>
      </div>
    </div>
    <div class="review-payment">
      <h2>Review & Payment</h2>
    </div>

    <div class="table-responsive cart_info">
      <table class="table table-condensed">
        <thead>
        <tr class="cart_menu">
          <td class="image">Item</td>
          <td class="description"></td>
          <td class="price">Price</td>
          <td class="quantity">Quantity</td>
          <td class="total">Total</td>
          <td></td>
        </tr>
        </thead>
        <tbody>
        <tr>
          <td class="cart_product">
            <a href=""><img src="<%= image_path '/uploads/cart/one.png' %>" alt=""></a>
          </td>
          <td class="cart_description">
            <h4><a href="">Colorblock Scuba</a></h4>
            <p>Web ID: 1089772</p>
          </td>
          <td class="cart_price">
            <p>$59</p>
          </td>
          <td class="cart_quantity">
            <div class="cart_quantity_button">
              <a class="cart_quantity_up" href=""> + </a>
              <input class="cart_quantity_input" type="text" name="quantity" value="1" autocomplete="off" size="2">
              <a class="cart_quantity_down" href=""> - </a>
            </div>
          </td>
          <td class="cart_total">
            <p class="cart_total_price">$59</p>
          </td>
          <td class="cart_delete">
            <a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
          </td>
        </tr>

        <tr>
          <td class="cart_product">
            <a href=""><img src="<%= image_path '/uploads/cart/one.png' %>" alt=""></a>
          </td>
          <td class="cart_description">
            <h4><a href="">Colorblock Scuba</a></h4>
            <p>Web ID: 1089772</p>
          </td>
          <td class="cart_price">
            <p>$59</p>
          </td>
          <td class="cart_quantity">
            <div class="cart_quantity_button">
              <a class="cart_quantity_up" href=""> + </a>
              <input class="cart_quantity_input" type="text" name="quantity" value="1" autocomplete="off" size="2">
              <a class="cart_quantity_down" href=""> - </a>
            </div>
          </td>
          <td class="cart_total">
            <p class="cart_total_price">$59</p>
          </td>
          <td class="cart_delete">
            <a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
          </td>
        </tr>
        <tr>
          <td class="cart_product">
            <a href=""><img src="<%= image_path '/uploads/cart/one.png' %>" alt=""></a>
          </td>
          <td class="cart_description">
            <h4><a href="">Colorblock Scuba</a></h4>
            <p>Web ID: 1089772</p>
          </td>
          <td class="cart_price">
            <p>$59</p>
          </td>
          <td class="cart_quantity">
            <div class="cart_quantity_button">
              <a class="cart_quantity_up" href=""> + </a>
              <input class="cart_quantity_input" type="text" name="quantity" value="1" autocomplete="off" size="2">
              <a class="cart_quantity_down" href=""> - </a>
            </div>
          </td>
          <td class="cart_total">
            <p class="cart_total_price">$59</p>
          </td>
          <td class="cart_delete">
            <a class="cart_quantity_delete" href=""><i class="fa fa-times"></i></a>
          </td>
        </tr>
        <tr>
          <td colspan="4">&nbsp;</td>
          <td colspan="2">
            <table class="table table-condensed total-result">
              <tr>
                <td>Cart Sub Total</td>
                <td>$59</td>
              </tr>
              <tr>
                <td>Exo Tax</td>
                <td>$2</td>
              </tr>
              <tr class="shipping-cost">
                <td>Shipping Cost</td>
                <td>Free</td>
              </tr>
              <tr>
                <td>Total</td>
                <td><span>$61</span></td>
              </tr>
            </table>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
    <div class="payment-options">
					<span>
						<label><input type="checkbox"> Direct Bank Transfer</label>
					</span>
					<span>
						<label><input type="checkbox"> Check Payment</label>
					</span>
					<span>
						<label><input type="checkbox"> Paypal</label>
					</span>
    </div>
  </div>
</section> <!--/#cart_items-->

app/views/shared/_header.html.erb
<header id="header"><!--header-->
  <div class="header_top"><!--header_top-->
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <div class="contactinfo">
            <ul class="nav nav-pills">
              <li><a href="#"><i class="fa fa-phone"></i> +2 95 01 88 821</a></li>
              <li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
            </ul>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="social-icons pull-right">
            <ul class="nav navbar-nav">
              <li><a href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div><!--/header_top-->

  <div class="header-middle">
    <div class="container">
      <div class="row">
        <div class="col-sm-4">
          <div class="logo pull-left">
            <%= link_to root_path do %>
                <img src="<%= image_path 'logo.png' %>" alt="E-shopper" width="139" height="39">
            <% end %>
          </div>
<!--           <div class="btn-group pull-right">
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                USA
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="#">Canada</a></li>
                <li><a href="#">UK</a></li>
              </ul>
            </div> -->

<!--             <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
                DOLLAR
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li><a href="#">Canadian Dollar</a></li>
                <li><a href="#">Pound</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-8">
          <div class="shop-menu pull-right">
            <ul class="nav navbar-nav cart_count">
                <%= render partial: 'shared/nav_bar_links_in_header' %>
            </ul>
          </div>
        </div> -->
      </div>
    </div>
  </div>

  <div class="header-bottom"><!--header-bottom-->
    <div class="container">
      <div class="row">
        <div class="col-sm-9">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div>
          <div class="mainmenu pull-left">
            <ul class="nav navbar-nav collapse navbar-collapse">
              <li><a href="index.html" class="active">Home</a></li>
              <li class="dropdown"><a href="#">Shop<i class="fa fa-angle-down"></i></a>
                <ul role="menu" class="sub-menu">
                  <li><a href="shop.html">Products</a></li>
                  <li><a href="product-details.html">Product Details</a></li>
                  <li><a href="checkout.html">Checkout</a></li>
                  <li><a href="cart.html">Cart</a></li>
                  <li><a href="login.html">Login</a></li>
                </ul>
              </li>
              <li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a>
                <ul role="menu" class="sub-menu">
                  <li><a href="blog.html">Blog List</a></li>
                  <li><a href="blog-single.html">Blog Single</a></li>
                </ul>
              </li>
              <li><a href="404.html">404</a></li>
              <li><a href="contact-us.html">Contact</a></li>
              <% if admin_signed_in? %>
                <li><a href="<%= admin_path %>"><b>АДМИНКА</b></a></li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="search_box pull-right">
            <input type="text" placeholder="Search"/>
          </div>
        </div>
      </div>
    </div>
  </div><!--/header-bottom-->
</header><!--/header-->

app/views/shared/_nav_bar_links_in_header.html.erb
<li><a href="#"><i class="fa fa-user"></i> Account</a></li>
<li><a href="#"><i class="fa fa-star"></i> Wishlist</a></li>
<li><a href="#"><i class="fa fa-crosshairs"></i> Checkout</a></li>

<% unless session[:carts].present? %>
    <li><a href="<%= carts_path %>"><i class="fa fa-shopping-cart"></i>Корзина</a></li>
<% else %>
    <li>
      <a href="<%= carts_path %>"><i class="fa fa-shopping-cart"></i><%= "Корзина(#{session[:carts].count})" %>
      </a>
    </li>
<% end %>

<li><a href="#"><i class="fa fa-lock"></i> Login</a></li>

app/views/shared/_sideBar.html.erb
<div class="left-sidebar">
  <h2>Category</h2>
  <div class="panel-group category-products" id="accordian"><!--category-productsr-->
    <% @categories.each_with_index do |category, index| %>
      <% if category.has_children? %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordian" href="#open_category_<%= index %>">
                <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                <%= category.title %>
              </a>
            </h4>
          </div>
          <div id="open_category_<%= index %>" class="panel-collapse collapse">
            <div class="panel-body">
              <ul>
                <% category.children.each do | subcategory| %>
                  <li><a href=""><%= subcategory.title %> </a></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <% elsif category.parent.present? %>
            <!-- Скрыть подкатегории -->
        <% else %>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title"><a href="<%= category_path(category) %>"><%= category.title %></a></h4>
            </div>
          </div>
        <% end %>
      <% end %>


  </div><!--/category-products-->

  <div class="brands_products"><!--brands_products-->
    <h2>Brands</h2>
    <div class="brands-name">
      <ul class="nav nav-pills nav-stacked">
        <% @brands.each do |brand| %>
            <li><a href="<%= brand_path(brand) %>"> <span class="pull-right">(<%= brand.products_count.nil?  ? '0' : brand.products_count  %>)</span><%= brand.title %></a></li>
        <%end %>
      </ul>
    </div>
  </div><!--/brands_products-->

  <div class="price-range">
    <h2>Price Range</h2>
    <div class="well">
      <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="600" data-slider-step="5" data-slider-value="[250,450]" id="sl2" ><br />
      <b>$ 0</b> <b class="pull-right">$ 600</b>
    </div>
  </div>

  <div class="shipping text-center"><!--shipping-->
    <img src="<%= image_path '/uploads/home/shipping.jpg' %> " alt="" />
  </div><!--/shipping-->
</div>